Kotlin. Homework #1. Task #2
Ythosa/spbu-kotlin-homeworks pull request #4
Opened 2022-03-06 21:09 UTC by Ythosa

2022-03-08 14:36 UTC, GirZ0n requested changes
Балдёжный код! Оставил небольшие замечания, ну чтобы другим не было обидно))

2022-03-08 14:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveFunctionally.kt
> +            throw InvalidBoundException(bound)
Давай здесь фигурные скобки поставим.

2022-03-08 14:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveFunctionally.kt
> +            yield(number)
И тут тоже скобки)

2022-03-08 14:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +            throw InvalidBoundException(bound)
И тут тоже скобки)

2022-03-08 14:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        val sieveArray = getSieveArray(bound)
У нас тут булевский массив, поэтому, как мне кажется, и название должно быть соответствующее) Например, `isPrime` или что-то такое.

2022-03-08 14:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        val sieveArray = getSieveArray(bound)
Ну и в других функция тоже нужно переименовать)

2022-03-08 14:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task2/task_2.kt
> +
Лишняя строка.

2022-03-08 14:36 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveGetPrimesUpToTheBoundaryTest.kt
> +        assertEquals(listOf<Int>(), sieve.getPrimesUpToTheBoundary(2))
Лучше использовать `emptyList`.

2022-03-08 15:43 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveFunctionally.kt
> +            throw InvalidBoundException(bound)
Кажется, автоформатирование съело все скобки

2022-03-08 15:45 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task2/task_2.kt
> +
Go style отделять return statement, sorry

2022-03-08 16:51 UTC, GirZ0n approved these changes
:fire:

2022-03-10 14:52 UTC, SpirinEgor requested changes

2022-03-10 14:52 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        val isPrimes = MutableList(bound) { index -> index !in 0..1 }
```kotlin
index > 1
```

2022-03-10 14:52 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        for (number in 2..intSqrt(bound)) {
Аккуратнее будет делать цикл до `number * number <= bound`, не надо будет возиться с извлечением корня и кастами туда обратно

2022-03-10 14:52 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        return extractPrimes(isPrimes)
Что-то какая-то лапша тут началась, создать список потом передавать его везде. Пусть `sieve` сам создаёт нужный список и возвращает его. `mapIndexedNotNull` тоже непонятно зачем куда-то отдельно выносить, заменить 1 вызов функции на другой.

2022-03-10 14:52 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieve.kt
> +interface EratosthenesSieve {
Решето Эратосфена это конкретный алгоритм, более того интерфейс никак не обозначает методы специфичные для него. Тут уместнее назвать по типу `PrimeNumbersExtractor`, а уже потом делать какие-то конкретные реализации пусть и с разными вариациями одного алгоритма.

Как альтернатива -- можешь этот интерфейс расширить до абстрактного класса с общей логикой между реализациями решета

2022-03-10 14:53 UTC, SpirinEgor commented
Мы же отдельно обсуждали самостоятельное усложнение задачек в домашках, зачем сразу же делать обратное?

2022-03-10 18:38 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        return extractPrimes(isPrimes)
Показалось, что так понятней, что происходит в коде

2022-03-10 18:41 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        for (number in 2..intSqrt(bound)) {
Не нравится цикл `while`

2022-03-10 18:55 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        for (number in 2..intSqrt(bound)) {
Детская травма использовать `while`

2022-03-11 08:50 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        return extractPrimes(isPrimes)
Наоборот стало менее понятным -- логика мизерная, а декомпозиция большая. Ну и как бы не надо тянуть логику из С, где создание массивов было чем-то сложным и требовало вынести куда-то в сторону.

2022-03-11 10:45 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task2/eratosthenesSieve/EratosthenesSieveImperative.kt
> +        return extractPrimes(isPrimes)
Хорошо (но я не тяну логику из C)

2022-03-12 06:43 UTC, nbirillo commented
А где проблема с jmh то? только добралась сюда

2022-03-12 09:59 UTC, Ythosa commented
> А где проблема с jmh то? только добралась сюда

Вы хотите сказать, у вас всё работает, или чего... :disappointed:

2022-03-18 13:04 UTC, merged