Kotlin. Homework #1. Task #3
Ythosa/spbu-kotlin-homeworks pull request #5
Opened 2022-03-08 18:51 UTC by Ythosa

2022-03-10 19:09 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/ui/Commands.kt
> +enum class Commands(val commandName: String) {
Тут не совсем уверен, что этот `enum` уместен. Не совсем понимаю, какую задачу он решает. Хочется как-то прямо здесь привязывать хендлеры, либо вообще этот этого `enum`'a отказаться

2022-03-10 19:11 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/ui/REPL.kt
> +    private fun printWelcomeMessage() = println("ʕ•́ᴥ•̀ʔっ Welcome to Performed Command Storage! ")
Можно сказать, что эта функция практически не имеет смысла, но, как мне кажется, `.start()` метод решает слишком многое и это повышает читабельность(?)

2022-03-11 08:47 UTC, illided requested changes

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/ImpossibleCancelCommandException.kt
> +class ImpossibleCancelCommandException : Exception("error: impossible cancel command")
Я думаю не надо создавать целую иерархию исключений под такую домашку)

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/PerformedCommandStorage.kt
> +    private val commands = Stack<Action>()
Stack достаточно старая штука, лучше использовать ArrayDeque
https://stackoverflow.com/questions/12524826/why-should-i-use-deque-over-stack

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/Action.kt
> +    fun apply(elements: LinkedList<Int>)
Я бы наверное посоветовал больше переходить на котлиновские коллекции, чтобы сразу привыкать как они работают. А то получается просто джава без точки с запятой)

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/MoveAction.kt
> +        for (index in listOf(firstIndex, secondIndex)) {
Ох жесть, а зачем так? Тут много индексов будет разных?) Мне кажется читабельнее будет ручками проверить.

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/MoveAction.kt
> +    private fun isIndexExists(index: Int, elements: List<Int>) = index >= 0 && index < elements.size
В котлине можно сделать `index in list.indices`

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/UnshiftAction.kt
> +class UnshiftAction(private val element: Int) : Action {
Наверное лучше поменять название на `PushFirst`

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/Commands.kt
> +enum class Commands(val commandName: String) {
Мне кажется норм) Если например придется перевести весь Repl на татарский, то можно будет просто подменить енам) Естественно надо будет покопаться немного, но это явно проще, чем если бы оно сразу было в хэндлерах.

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/Handler.kt
> +abstract class Handler {
В аду есть отдельный котел для тех кто называет свой класс просто `Handler` :)

2022-03-11 08:47 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/Cast.kt
> +fun interface Cast {
Это прям обязательный интерфейс?)

2022-03-11 08:48 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/REPL.kt
> +    private fun printWelcomeMessage() = println("ʕ•́ᴥ•̀ʔっ Welcome to Performed Command Storage! ")
Я бы сказал здесь это дело вкуса

2022-03-11 10:49 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/ImpossibleCancelCommandException.kt
> +class ImpossibleCancelCommandException : Exception("error: impossible cancel command")
Как мне к этому относиться?)

2022-03-11 11:01 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/MoveAction.kt
> +    private fun isIndexExists(index: Int, elements: List<Int>) = index >= 0 && index < elements.size
Не смог найти, за какую сложность он работает :crying_cat_face:

2022-03-11 11:05 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/Handler.kt
> +abstract class Handler {
Ничего страшного. Какое название Вас устроит?

2022-03-11 11:08 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/Cast.kt
> +fun interface Cast {
В двух местах используется, не вижу в нем ничего плохого :innocent:

2022-03-11 11:15 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/Action.kt
> +    fun apply(elements: LinkedList<Int>)
Хорошо. Тогда в интерфейсах заменю `LinkedList` на `List`, но подкладывать всё же буду `LinkedList`?

2022-03-11 11:18 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/MoveAction.kt
> +    private fun isIndexExists(index: Int, elements: List<Int>) = index >= 0 && index < elements.size
`list.indices` генерирует IntRange за O(1)
https://github.com/JetBrains/kotlin/tree/6a670dc5f38fc73eb01d754d8f7c158ae0176ceb/libraries/stdlib/src/kotlin/collections/Collections.kt#L214
И IntRange проверяет наличие за O(1)
https://github.com/JetBrains/kotlin/tree/6a670dc5f38fc73eb01d754d8f7c158ae0176ceb/core/builtins/src/kotlin/Ranges.kt#L48

2022-03-11 11:19 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/UnshiftAction.kt
> +class UnshiftAction(private val element: Int) : Action {
А не жсеры?)  Я думаю их больше будет)

2022-03-11 11:19 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/MoveAction.kt
> +    private fun isIndexExists(index: Int, elements: List<Int>) = index >= 0 && index < elements.size
Здорово!

2022-03-11 11:23 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/Handler.kt
> +abstract class Handler {
Хотя бы `CLIHandler` или `ActionREPLHandler`. Но тут еще надо будет подумать над названием.
И не надо "вы", тем более с большой буквы :)

2022-03-11 11:25 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/ImpossibleCancelCommandException.kt
> +class ImpossibleCancelCommandException : Exception("error: impossible cancel command")
Ну здесь можно оставить, но в будущем лучше по минимуму плодить таких сущностей. Иначе можно перестараться и запутаться в кастомных исключениях.

2022-03-11 11:27 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/Action.kt
> +    fun apply(elements: LinkedList<Int>)
Да, так кажется лучше.

2022-03-11 11:45 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/UnshiftAction.kt
> +class UnshiftAction(private val element: Int) : Action {
Тогда `PushFirst` и `PushBack` ?

2022-03-11 11:50 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/ImpossibleCancelCommandException.kt
> +class ImpossibleCancelCommandException : Exception("error: impossible cancel command")
Хорошо

2022-03-16 10:01 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/MoveAction.kt
> +        for (index in listOf(firstIndex, secondIndex)) {
Так, соре что так долго не отвечал) Уведомление не пришло почему-то
Разве одни и те же сообщения должны быть? У тебя ведь совершенно разная роль у этих индексов.
Еще мне названия не нравятся, наверное здесь сделать также `from` и `to`

2022-03-16 10:01 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/commandStorage/actions/UnshiftAction.kt
> +class UnshiftAction(private val element: Int) : Action {
Ага

2022-03-16 10:02 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/Cast.kt
> +fun interface Cast {
Ну лан, здесь можно оставить тогда)

2022-03-19 08:43 UTC, illided requested changes
Все :fire: 
Когда поправишь кидай review уже на Егора

2022-03-19 08:43 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/PushBackHandler.kt
> +            val (number) = this.extractArguments(arguments, arrayOf(intCast))
Думаю это не самый читабельный способ достать первый элемент из списка)

2022-03-19 08:43 UTC, illided commented on src/test/kotlin/homeworks/homework1/task3/actions/PushFirstActionTest.kt
> +        private const val unshiftValue = 1
А здесь unshift остался еще

2022-03-19 08:43 UTC, illided commented on src/test/kotlin/homeworks/homework1/task3/commandStorage/PerformedCommandStorageTest.kt
> +        commandStorage = PerformedCommandStorage()
Можно еще и изначально прописать
`commandStorage = PerformedCommandStorage` 
и не делать его nullable расставляя везде `!!`

2022-03-19 09:49 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/PushBackHandler.kt
> +            val (number) = this.extractArguments(arguments, arrayOf(intCast))
Во-первых, мы достаем не первый элемент из списка, а все аргументы, в данном случае аргумент единственный, что показательно

2022-03-19 09:52 UTC, Ythosa commented on src/test/kotlin/homeworks/homework1/task3/commandStorage/PerformedCommandStorageTest.kt
> +        commandStorage = PerformedCommandStorage()
Вы, как и я, упустили более kotlin way, более элегантное решение! 
```kotlin
private lateinit var commandStorage: PerformedCommandStorage
```

2022-03-21 11:24 UTC, illided commented on src/test/kotlin/homeworks/homework1/task3/commandStorage/PerformedCommandStorageTest.kt
> +        commandStorage = PerformedCommandStorage()
Не упустил, мне просто не нравится `lateinit` :)
Он пришел к нам не от мира сего (из андроида) и с ним может быть связано куча багов и неприятностей

2022-03-21 11:27 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/PushBackHandler.kt
> +            val (number) = this.extractArguments(arguments, arrayOf(intCast))
Я думаю сходу не так много людей поймет что деструкцию можно делать на списке из одного элемента 
Например я, который пару минут глядел на этот код :) 
Согласен дело вкуса, но когда приходишь чинить свой код через год после написания такое может аукнуться

2022-03-21 12:04 UTC, Ythosa commented on src/test/kotlin/homeworks/homework1/task3/commandStorage/PerformedCommandStorageTest.kt
> +        commandStorage = PerformedCommandStorage()
> Не упустил, мне просто не нравится `lateinit` :) Он пришел к нам не от мира сего (из андроида) и с ним может быть связано куча багов и неприятностей

Не думаю, что в тестах можно столкнуться с жуткими неприятностями :))

2022-03-21 12:05 UTC, Ythosa commented on src/main/kotlin/homeworks/homework1/task3/ui/handlers/PushBackHandler.kt
> +            val (number) = this.extractArguments(arguments, arrayOf(intCast))
Попишите на джаваскриптике, там деструкция повеселее

2022-03-22 17:24 UTC, SpirinEgor commented on build.gradle.kts
> +    autoCorrect = true
Правда ли что в этом случае CI не будет репортить ошибку? Ну то есть будет себе на воркера клонить проект и там его локально успешно автоматически исправлять.

2022-03-22 19:48 UTC, Ythosa commented on build.gradle.kts
> +    autoCorrect = true
Не правда. Он наругается, а потом только исправит.

Т.е.:
- 1 запуск - ругается и исправляет, если может
- 2 запуск - если что-то смог исправить, ругаться будет меньше

Такие дела :)

2022-03-23 09:09 UTC, SpirinEgor approved these changes

2022-03-23 09:09 UTC, merged